from PySide2 import QtCore, QtGui, QtWidgets

def archStyle():
	
	palette = QtGui.QPalette()
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
	brush = QtGui.QColor(40, 44, 64)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
	brush = QtGui.QColor(60, 66, 96)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
	brush = QtGui.QColor(50, 55, 80)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
	brush = QtGui.QColor(20, 22, 32)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
	brush = QtGui.QColor(26, 29, 42)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
	brush = QtGui.QColor(40, 44, 64)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
	brush = QtGui.QColor(20, 22, 32)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
	brush = QtGui.QColor(255, 255, 220)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
	brush = QtGui.QColor(40, 44, 64)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
	brush = QtGui.QColor(60, 66, 96)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
	brush = QtGui.QColor(50, 55, 80)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
	brush = QtGui.QColor(20, 22, 32)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
	brush = QtGui.QColor(26, 29, 42)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
	brush = QtGui.QColor(40, 44, 64)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
	brush = QtGui.QColor(20, 22, 32)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
	brush = QtGui.QColor(255, 255, 220)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
	brush = QtGui.QColor(20, 22, 32)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
	brush = QtGui.QColor(40, 44, 64)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
	brush = QtGui.QColor(60, 66, 96)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
	brush = QtGui.QColor(50, 55, 80)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
	brush = QtGui.QColor(20, 22, 32)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
	brush = QtGui.QColor(26, 29, 42)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
	brush = QtGui.QColor(20, 22, 32)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
	brush = QtGui.QColor(20, 22, 32)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
	brush = QtGui.QColor(40, 44, 64)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
	brush = QtGui.QColor(40, 44, 64)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
	brush = QtGui.QColor(40, 44, 64)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
	brush = QtGui.QColor(255, 255, 220)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
	return palette

def darkStyle():

	palette = QtGui.QPalette()
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
	brush = QtGui.QColor(67, 67, 67)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
	brush = QtGui.QColor(100, 100, 100)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
	brush = QtGui.QColor(83, 83, 83)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
	brush = QtGui.QColor(26, 26, 26)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
	brush = QtGui.QColor(44, 44, 44)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
	brush = QtGui.QColor(29, 29, 29)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
	brush = QtGui.QColor(67, 67, 67)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
	brush = QtGui.QColor(33, 33, 33)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
	brush = QtGui.QColor(255, 255, 220)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
	brush = QtGui.QColor(67, 67, 67)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
	brush = QtGui.QColor(100, 100, 100)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
	brush = QtGui.QColor(83, 83, 83)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
	brush = QtGui.QColor(26, 26, 26)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
	brush = QtGui.QColor(44, 44, 44)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
	brush = QtGui.QColor(29, 29, 29)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
	brush = QtGui.QColor(67, 67, 67)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
	brush = QtGui.QColor(33, 33, 33)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
	brush = QtGui.QColor(255, 255, 220)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
	brush = QtGui.QColor(26, 26, 26)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
	brush = QtGui.QColor(67, 67, 67)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
	brush = QtGui.QColor(100, 100, 100)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
	brush = QtGui.QColor(83, 83, 83)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
	brush = QtGui.QColor(26, 26, 26)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
	brush = QtGui.QColor(44, 44, 44)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
	brush = QtGui.QColor(26, 26, 26)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
	brush = QtGui.QColor(255, 255, 255)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
	brush = QtGui.QColor(26, 26, 26)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
	brush = QtGui.QColor(67, 67, 67)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
	brush = QtGui.QColor(67, 67, 67)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
	brush = QtGui.QColor(67, 67, 67)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
	brush = QtGui.QColor(255, 255, 220)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
	brush = QtGui.QColor(0, 0, 0)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)

	return palette

def autoStyle(color = [67, 67, 67]):

	rgb = dict()
	rgb["r"] = color[0] 
	rgb["g"] = color[1] 
	rgb["b"] = color[2] 
	palette = QtGui.QPalette()

	# if rgb["r"] > 125 or rgb["g"] > 125 or rgb["b"] > 125:
	# 	#LIGHT
	# 	colorWindowText   	=	QtGui.QColor(0, 0, 0)
	# 	colorButton  		=	QtGui.QColor(rgb["r"], rgb["g"], rgb["b"])
	# 	colorLight 			=	QtGui.QColor(round(rgb["r"]*0.75), round(rgb["g"]*0.75), round(rgb["b"]*0.75))
	# 	colorMidlight  		=	QtGui.QColor(round(rgb["r"]*0.85), round(rgb["g"]*0.85), round(rgb["b"]*0.85))
	# 	colorDark  			=	QtGui.QColor(round(rgb["r"]*0.25), round(rgb["g"]*0.25), round(rgb["b"]*0.25))
	# 	colorMid  			=	QtGui.QColor(round(rgb["r"]*2), round(rgb["g"]*2), round(rgb["b"]*2))
	# 	colorText  			=	QtGui.QColor(0, 0, 0)
	# 	colorBrightText  	=	QtGui.QColor(0, 0, 0)
	# 	colorButtonText  	=	QtGui.QColor(0, 0, 0)
	# 	colorBase 			=	QtGui.QColor(round(rgb["r"]*1.9), round(rgb["g"]*1.9), round(rgb["b"]*1.9))
	# 	colorWindow 		=	QtGui.QColor(rgb["r"], rgb["g"], rgb["b"])
	# 	colorShadow 		=	QtGui.QColor(255, 255, 255)
	# 	colorAlternateBase 	=	QtGui.QColor(round(rgb["r"]*0.7), round(rgb["g"]*0.7), round(rgb["b"]*0.7))
	# 	colorToolTipBase 	=	QtGui.QColor(0, 0, 0)
	# 	colorToolTipText 	=	QtGui.QColor(255, 255, 255)

	# else:
	#DARK
	colorWindowText   	=	QtGui.QColor(255, 255, 255)
	colorButton  		=	QtGui.QColor(rgb["r"], rgb["g"], rgb["b"])
	colorLight 			=	QtGui.QColor(round(rgb["r"]*1.5), round(rgb["g"]*1.5), round(rgb["b"]*1.5))
	colorMidlight  		=	QtGui.QColor(round(rgb["r"]*1.25), round(rgb["g"]*1.25), round(rgb["b"]*1.25))
	colorDark  			=	QtGui.QColor(round(rgb["r"]*2.5), round(rgb["g"]*2.5), round(rgb["b"]*2.5))
	colorMid  			=	QtGui.QColor(round(rgb["r"]*0.5), round(rgb["g"]*0.5), round(rgb["b"]*0.5))
	colorText  			=	QtGui.QColor(255, 255, 255)
	colorBrightText  	=	QtGui.QColor(255, 255, 255)
	colorButtonText  	=	QtGui.QColor(255, 255, 255)
	colorBase 			=	QtGui.QColor(round(rgb["r"]*0.4), round(rgb["g"]*0.4), round(rgb["b"]*0.4))
	colorWindow 		=	QtGui.QColor(rgb["r"], rgb["g"], rgb["b"])
	colorShadow 		=	QtGui.QColor(0, 0, 0)
	colorAlternateBase 	=	QtGui.QColor(round(rgb["r"]*0.7), round(rgb["g"]*0.7), round(rgb["b"]*0.7))
	colorToolTipBase 	=	QtGui.QColor(255, 255, 220)
	colorToolTipText 	=	QtGui.QColor(0, 0, 0)

	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Highlight, 	  QtGui.QColor(204,186,47))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.WindowText, colorWindowText)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Button, colorButton)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Light, colorLight)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Midlight, colorMidlight)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Dark, colorDark)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Mid, colorMid)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Text, colorText)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.BrightText, colorBrightText)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, colorButtonText)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Base, colorBase)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Window, colorWindow)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Base, colorBase)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Shadow, colorShadow)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, colorAlternateBase)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, colorToolTipBase)
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, colorToolTipText)

	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, colorButtonText)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Button, colorWindow)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Light, colorLight)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, colorMidlight)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, colorDark)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, colorLight)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Text, colorButtonText)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, colorButtonText)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, colorButtonText)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Base, colorMid)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Window, colorWindow)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, colorShadow)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, colorAlternateBase)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, colorButtonText)
	palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, colorShadow)

	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, colorMidlight)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Button, colorWindow)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Light, colorLight)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, colorMidlight)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, colorDark)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, colorLight)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Text, colorDark)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, colorButtonText)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, colorMidlight)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Base, colorWindow)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Window, colorWindow)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, colorShadow)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, colorWindow)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, colorButtonText)
	palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, colorShadow)

	return palette

def purpleStyle():

	palette = QtGui.QPalette()
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Highlight, 	  QtGui.QColor(204,186,47))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.WindowText, 	  QtGui.QColor(255, 255, 255))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Button, 		  QtGui.QColor(114,112,177))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Light, 		  QtGui.QColor(100, 100, 100))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Midlight,	  QtGui.QColor(107,121,212))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Dark, 		  QtGui.QColor(26, 26, 26))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Mid, 		  QtGui.QColor(44, 44, 44))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Text, 		  QtGui.QColor(255, 255, 255))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.BrightText,    QtGui.QColor(255, 255, 255))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ButtonText,    QtGui.QColor(255, 255, 255))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Base, 		  QtGui.QColor(54,33,130))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, QtGui.QColor(156,132,188))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Window, 		  QtGui.QColor(132,92,164))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Shadow, 		  QtGui.QColor(0, 0, 0))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText,   QtGui.QColor(0, 0, 0))
	palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase,   QtGui.QColor(255, 255, 220))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, QtGui.QColor(255, 255, 255))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Button, QtGui.QColor(67, 67, 67))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Light, QtGui.QColor(100, 100, 100))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, QtGui.QColor(83, 83, 83))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, QtGui.QColor(26, 26, 26))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, QtGui.QColor(44, 44, 44))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Text, QtGui.QColor(255, 255, 255))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, QtGui.QColor(255, 255, 255))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, QtGui.QColor(255, 255, 255))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Base, QtGui.QColor(29, 29, 29))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Window, QtGui.QColor(67, 67, 67))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, QtGui.QColor(0, 0, 0))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, QtGui.QColor(33, 33, 33))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, QtGui.QColor(255, 255, 220))
	# palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, QtGui.QColor(0, 0, 0))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, QtGui.QColor(26, 26, 26))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Button, QtGui.QColor(67, 67, 67))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Light, QtGui.QColor(100, 100, 100))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, QtGui.QColor(83, 83, 83))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, QtGui.QColor(26, 26, 26))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, QtGui.QColor(44, 44, 44))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Text, QtGui.QColor(26, 26, 26))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, QtGui.QColor(255, 255, 255))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, QtGui.QColor(26, 26, 26))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Base, QtGui.QColor(67, 67, 67))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Window, QtGui.QColor(67, 67, 67))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, QtGui.QColor(0, 0, 0))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, QtGui.QColor(67, 67, 67))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, QtGui.QColor(255, 255, 220))
	# palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, QtGui.QColor(0, 0, 0))

	return palette